#!/bin/bash


if [ -z "$SERVICE_DATASTORE" ]; then
    echo "This script is meant to be run through 'compose' to work properly." >&2
    exit 1
fi

. "$CHARM_PATH/lib/common"

# Combined commands to be run as zato user
zato_commands="/opt/zato/current/bin/zato stop /opt/zato/env/qs-1/server1/"

# Execute commands as zato user
if ! exec_as_zato_in_container "$zato_commands"; then
    printf "Error: Failed to execute zato commands in container '%s'.\n" "$CONTAINER_NAME" >&2
    return 1
fi

printf "Zato stopped successfully in container '%s'.\n" "$CONTAINER_NAME" >&2

