#!/bin/bash

. lib/common

DOMAIN=$(relation-get domain) || exit 1
#IP_HOST=$(hostname -I | awk '{print $1}')

set -e
keycloak:generate-key-if-not-exist "$DOMAIN"


config-add "\
services:
  $MASTER_BASE_SERVICE_NAME:
    environment:
      KC_HOSTNAME: \"$DOMAIN\"
      KC_PROXY: edge
      KC_HTTP_ENABLED: \"true\"
      KC_HOSTNAME_STRICT: \"false\"
"

