#!/bin/bash

DOMAIN=$(relation-get domain) || exit 1
DEST_LETSENCRYPT_FULLCHAIN="$SERVICE_DATASTORE/opt/zato/letsencrypt-fullchain.pem"
CUSTOM_CREATE_LB_PATH="/opt/zato/3.2.0/code/zato-cli/src/zato/cli/create_lb.py"

set -e

mkdir -p "${DEST_LETSENCRYPT_FULLCHAIN%/*}"

cat $DATASTORE/letsencrypt/etc/letsencrypt/live/$DOMAIN/{fullchain,privkey}.pem > "$DEST_LETSENCRYPT_FULLCHAIN" || exit 1

# adding custom config file to handle https in load_balancer with letsencrypt-fullchain certificate

config-add "\
services:
  $MASTER_BASE_SERVICE_NAME:
    volumes:
      - $BASE_CHARM_PATH/resources/$CUSTOM_CREATE_LB_PATH:$CUSTOM_CREATE_LB_PATH
      - $DEST_LETSENCRYPT_FULLCHAIN:/opt/zato/letsencrypt-fullchain.pem
"

info "Configured $SERVICE_NAME load_balancer with HTTPS support."